* Skip the noexec/nodev test when running --print-debs or other operations   that do not involve building systems.
r49840

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -307,6 +307,10 @@ if am_doing_phase first_stage second_stage; then
   if [ -x /usr/bin/id ] && [ `id -u` -ne 0 ]; then
     error 1 NEEDROOT "debootstrap can only run as root"
   fi
+  # Ensure that we can create working devices and executables on the target.
+  if ! check_sane_mount "$TARGET"; then
+    error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
+  fi
 fi
 
 if [ ! -e "$SCRIPT" ]; then
@@ -347,13 +351,6 @@ else
   exec 4>&1
   exec >>"$TARGET/debootstrap/debootstrap.log"
   exec 2>&1
-fi
-
-###########################################################################
-
-# Ensure that we can create working devices and executables on the target.
-if ! check_sane_mount "$TARGET"; then
-  error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
 fi
 
 ###########################################################################
