* Emit an error if we cannot create working devices or executables on the   target (based on work by Bastian Kleineidam; closes: #233798).
r49822

diff --git a/debootstrap b/debootstrap
--- a/debootstrap
+++ b/debootstrap
@@ -351,6 +351,13 @@ fi
 
 ###########################################################################
 
+# Ensure that we can create working devices and executables on the target.
+if ! check_sane_mount "$TARGET"; then
+  error 1 NOEXEC "Cannot install into target '$TARGET' mounted with noexec or nodev"
+fi
+
+###########################################################################
+
 if [ "$UNPACK_TARBALL" ]; then
   if [ "${UNPACK_TARBALL#/}" = "$UNPACK_TARBALL" ]; then
     error 1 TARPATH "Tarball must be given a complete path"
